Arduino: PID_Initial.ino File Reference
PID_Initial.ino File Reference
Sets up the PID algorithm.
Functions
void PID_initial ()
sets up PID
Detailed Description
Sets up the PID algorithm.
Contains one function. Initializes pins and interrupt events from encoder needed for the PID algorithm.
Definition in file PID_Initial.ino.
Function Documentation
PID_initial()
void PID_initial ()
sets up PID
Sets the Arduino pins connected to ENA, ENB, IN1, IN2, IN3 and IN4 to output.
Sets the Arduino pins connected to encoders to input.
Sets up interrupts on the encoder pins (these can only be set to specific pins on the Board). The interrupt is triggered on the RISING edge of the signal. Functions are called on this interrupt event.
Sets the AutoPID objects leftPID and rightPID to have a time step in milliseconds for the PID calculation.
Returns
void
Definition at line 17 of file PID_Initial.ino.
                    {
     pinMode(motor_ENA, OUTPUT);
     pinMode(motor_ENB, OUTPUT);
     pinMode(motor_IN1, OUTPUT);
     pinMode(motor_IN2, OUTPUT);
     pinMode(motor_IN3, OUTPUT);
     pinMode(motor_IN4, OUTPUT);
     pinMode(encoder_L_C1, INPUT);
     pinMode(encoder_R_C1, INPUT);
     attachInterrupt(digitalPinToInterrupt(encoder_L_C1), encoderLeft, RISING);
     attachInterrupt(digitalPinToInterrupt(encoder_R_C1), encoderRight, RISING);
     leftPID.setTimeStep(4);
     rightPID.setTimeStep(4);
 }
References encoder_L_C1, encoder_R_C1, encoderLeft(), encoderRight(), leftPID, motor_ENA, motor_ENB, motor_IN1, motor_IN2, motor_IN3, motor_IN4, and rightPID.
Referenced by setup().