Arduino: stopMotion.ino File Reference
stopMotion.ino File Reference
Stops robot.
Functions
void stopMotion ()
Commands both motors to stop spinning.
Detailed Description
Stops robot.
Stops all motion of the robot. Overwrites everything.
Definition in file stopMotion.ino.
Function Documentation
stopMotion()
void stopMotion ()
Commands both motors to stop spinning.
Returns
void
Definition at line 12 of file stopMotion.ino.
                   {
   motor(Left, Stop, Stop);
   motor(Right, Stop, Stop);
   currentMotion = Stop;
   // Clear the enocder counters. //
   countLeft = 0;
   countRight = 0;
 }
References countLeft, countRight, currentMotion, Left, motor(), Right, and Stop.
Referenced by decider(), and moveDirection().